# fly.toml app configuration file generated for orbitea-service on 2023-07-30T21:21:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "orbitea-service"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
